---
title: "Template-Analysis"
output:
  html_document:
   code_folding: hide
   df_print: paged
   toc: yes
   toc_float: no
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, warning = FALSE) 

source(here::here("00_packages.R"))
```

```{r load data}
metaviz_long <- readRDS(here::here("data", "metaviz_long.rds"))
```

# Explore Data for My-Project

## By Variable Category {.tabset}

### ID's
```{r fig.width= 10}
id_plot <- metaviz_long %>% 
      drop_na(value) %>% 
      filter(key_category == "ID's") %>%
      ggplot(aes(key_name_label, syear)) +
      geom_count(col = "#440154FF") +
      coord_flip() +
      theme(legend.position = "right") +
      scale_x_discrete(labels = wrap_format(40)) +
      scale_y_continuous(limits = c(1998, 2018), breaks = seq(1998, 2018, 2)) +
      labs(title = "Number of observations for selected SOEP variables from 1998 - 2018",
           subtitle = "Size indicates number of observations",
           y = "", x = "") 

id_plot
```

### Survey
```{r fig.width= 10}
survey_plot <- metaviz_long %>%
  drop_na(value) %>%
  filter(key_category == "Survey") %>%
  ggplot(aes(key_name_label, syear)) +
  geom_count(col = "#3B528BFF") +
  coord_flip() +
  theme(legend.position = "right") +
  scale_x_discrete(labels = wrap_format(40)) +
  scale_y_continuous(limits = c(1998, 2018),
                     breaks = seq(1998, 2018, 2)) +
  labs(
    title = "Number of observations for selected SOEP variables from 1998 - 2018",
    subtitle = "Size indicates number of observations",
    y = "",
    x = ""
  ) 

survey_plot
```

### Demography {.active}
```{r fig.width= 10}
dem_plot <- metaviz_long %>%
  drop_na(value) %>%
  filter(key_category == "Demography") %>%
  ggplot(aes(key_name_label, syear)) +
  geom_count(col = "#21908CFF") +
  coord_flip() +
  theme(legend.position = "right") +
  scale_x_discrete(labels = wrap_format(40)) +
  scale_y_continuous(limits = c(1998, 2018),
                     breaks = seq(1998, 2018, 2)) +
  labs(
    title = "Number of observations for selected SOEP variables from 1998 - 2018",
    subtitle = "Size indicates number of observations",
    y = "",
    x = ""
  )

dem_plot
```

### Psychol. Measures
```{r fig.height = 25, fig.width= 10}
psych_plot <- metaviz_long %>%
  drop_na(value) %>%
  filter(key_category == "Psych. Measure") %>%
  ggplot(aes(key_name_label, syear)) +
  geom_count(col = "#5DC863FF") +
  coord_flip() +
  theme(legend.position = "right") +
  scale_x_discrete(labels = wrap_format(40)) +
  scale_y_continuous(limits = c(1998, 2018),
                     breaks = seq(1998, 2018, 2)) +
  labs(
    title = "Number of observations for selected SOEP variables from 1998 - 2018",
    subtitle = "Size indicates number of observations",
    y = "",
    x = ""
  ) 

psych_plot
```

### Other
```{r fig.width= 10}
other_plot <- metaviz_long %>%
  drop_na(value) %>%
  filter(key_category == "Other") %>%
  ggplot(aes(key_name_label, syear)) +
  geom_count(col = "#FDE725FF") +
  coord_flip() +
  theme(legend.position = "right") +
  scale_x_discrete(labels = wrap_format(40)) +
  scale_y_continuous(limits = c(1998, 2018),
                     breaks = seq(1998, 2018, 2)) +
  labs(
    title = "Number of observations for selected SOEP variables from 1998 - 2018",
    subtitle = "Size indicates number of observations",
    y = "",
    x = ""
  ) 

other_plot
```

# Supplement

## resources
- row names to column: https://stackoverflow.com/questions/29511215/convert-row-names-into-first-column
- age categories: https://ggplot2.tidyverse.org/reference/cut_interval.html
- wrap label names: https://stackoverflow.com/questions/21878974/auto-wrapping-of-labels-via-labeller-label-wrap-in-ggplot2
